### ISSUE TITLE
Add Summation and Reduction features to form-link aggregation

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#112]
Currently the aggregation functionality handles counts from a single column across multiple locations / submissions and needs to be able to handle summing numbers from multiple columns across multiple locations / submissions.

### Todo
- [ ] **Reduction** - Add columns together from the mapspec (`['colA', 'colB', ..., colN'] => row['colA'] + row['colB'] + ... + row['colN'] => row.metric`)
- [ ] **Summation** - Add row values vs counting `yes / no`s (`rowA.metric + rowB.metric + ... + rowN.metric => aggregatedMetric`)
- [ ] **Example layer** - The result of this development should include one or two layers the data team can use as examples to build out the rest of the live link layers
