### ISSUE TITLE
Design different Map UI for Rohingya

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#113]
UNICEF isn't too crazy about our standard UI and would like something "more visually appealing", this is going to be a very public facing site so we should really aim to impress!

### Todo
- [ ] **Wireframes** - They said that service mapping feels a little crowded, are there layout changes we can do to reduce the visual overload (from all our awesome features!)
- [ ] **Mockups** - Lets get a few (3-4?) high-level mockups going to share with them to get feedback
- [ ] **Feedback** - We won't have time for more than 1 or 2 quick rounds of design, let's get see what they like and move forward from there!
