### ISSUE TITLE
Move layer grouping logic into the site-config

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#130]
This allows a single layer to be in different groups across different sites.

### Tasks
- [x] Save layer groups from `site-config` in LAYERS store
- [x] Render groups / layers from LAYERS.groups in the Menu component
- [x] Render groups from layer if no groups in LAYERS (deprecated previous functionality)

**After merging gisida(-react) PRs**
- [x] Convert `service-mapping` config to new layers schema (onaio/service-mapping#125)
- [ ] Convert `irfsomalia` [config](https://github.com/onaio/irfsomalia/blob/refactor-to-use-gisida/public/config/site-config.json) to new layers schema
- [ ] Convert `rohingya` [config](https://github.com/onaio/rohingya/blob/master/public/config/site-config.json) to new layers schema
