### ISSUE TITLE
Gisida + Reveal Integration

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#263]
Several core changes will need to happen in the gisida and gisida-react repos to meet the needs of the Reveal Web UI.

- [ ] Create `reveal` branches from newest code, will equate to gisida/-react `v1.2.0` @KipSigei @kahummer 
- [x] Make sure gisida's stores are compatible with reveal's (coupled with onaio/reveal-frontend#4)
- [ ] Add map-mouse-events extensibility to override default `handleFeatureClick()` (#264)
- [ ] Ingest reveal's admin/boundary hierarchy (coupled with onaio/reveal-frontend#8)
- [ ] Set detail view sidebar to be open by default (#265)

**Comment by cKellyDesign** [comment]
Closing this issue as Gisida Map / State integration in Reveal has been handled almost entirely in Reveal and there are other tickets when Gisida/-React updates were necessary.
