### ISSUE TITLE
Add Updated Gisida Roadmap for 2020

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#445]
As a core product Gisida needs to have a Roadmap which we can align and track the ongoing development of the GIsida repositories.

* [x] Draft Gisida's Vision, Themes, and Goals
* [x] Q2-4 Roadmap Meeting to establish the 2020 Roadmap
* [x] Retroactively Roadmap Q1
* [x] Prioritize Story Items
* [x] Add Roadmap to `/docs/roadmaps/2020.md`
* [x] Meeting to Review and Populate Quarterly Tables
* [x] Update Roadmap at `/docs/roadmaps/2020.md`

[Google Doc](https://docs.google.com/document/d/19HfeDMFaHhPmkBY0gXpoJyz1R5DMjtWeMnDOImYeaiA/edit?usp=sharing)

Epic: https://github.com/onaio/gisida/issues/454

**Comment by cKellyDesign** [comment]
## Vision
Gisida is a library of GIS-centric React+Redux components and utilities for client SPAs.

### The Why
To rapidly integrate and deploy GIS centric features across Ona products.

### The How
By standardizing and streamlining implementation of GIS centric features.


### The What
A modern library of GIS centric modular, portable, and reusable React+Redux tooling.

**Comment by cKellyDesign** [comment]
## Themes and Goals
These categorizations of work should correlate to Avaza Projects and Tasks.

1. **Consolidation**
  a. Converging Divergent Features / Branches
  b. Standardizing Custom Features
  c. Gisida React => Gisida?

2. **Operational Support**
  a. Support Triaging Protocols
  b. Engineering Support
  c. Client Driven Feature Development

3. **Modernization**
  a. FE Standardization
  b. Migrating Generic Components
  c. Mapbox React Component

4. **Gisida as a Package Library**
  a. Gisida 2.0 Implementation Strategy
  b. Package Development
  c. Storybooks

5. **Project Workflow and Repo Health**
  a. Project Management Protocols
  b. Service Integrations
  c. Dependency Maintenance
  d. Workflow Optimization
  e. Technical Documentation

6. **Product Definition and Development**
  a. Product Roadmap
  b. Feature Documentation
  c. Feature Development

**Comment by cKellyDesign** [comment]
## Roadmapping Meeting Agenda
1. Review, Deliberate, and Define Themes and Goals
2. Brainstorm Roadmap Tasks which fall into one or more theme/goal
3. Assign Prioritization to Roadmap Tasks
4. Populate Quarterly Roadmap Tables with Tasks
