### ISSUE TITLE
Project Management Documentation

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#454]
This is an epic level ticket tracking work towards documenting:

- [ ] the Roadmap
- [ ] the Structure of the project's Sprint Cycle
- [ ] the Structure and Agenda of the Weekly Meetings
  - [ ] the Requirements of PMs going into the Client focused meetings
  - [ ] the Requirements of Devs going into the Core focused meetings
- [ ] the Tools and Methods of checking the teams' statuses
- [ ] the Tools and Methods of Issue Upkeep
- [ ] the MVP Requirements for Issues and PRs
- [ ] the Requirements and Protocols for requests:
  - [ ] New Clients
  - [ ] Client Operational Support
  - [ ] Engineering Operational Support
  - [ ] New Core Features
