### ISSUE TITLE
Check if gisida sites using oauth are working as expected

### ISSUE THREAD

**Issue by samwata** [onaio/gisida#497]
We have had issues with gisida sites using oauth forms where it throws 404 error when logging in.
The reason why we are getting this error is that we are linking a form to self so that to get a public CSV that we use to check permissions before a user logs in.
The returned CSV from a form linked to itself throws 404 error even when accessing the file from Ona.
Deleting the linked file and relinking the form again does not seem to solve the issue

#### The process we have been using to solve the issue
1. Download the form from [help project on onasupport](https://ona.io/onahelp/37394)
2. Export the CSV file from the form
3. Upload the form to a project in client's account
4. Import the exported CSV using [import CSV](https://help.ona.io/knowledge-base/how-do-i-import-data-to-a-form-using-import-csv/) feature to the newly uploaded form
5. Give at least `Can View and Download` permissions to all users in that CSV you exported to a project where you uploaded the form
6. Link the form to itself so that you can generate a live link to CSV file format to that form
7. Give the ID of the linked CSV to a gisida technical team to change the oauth file in site config and deploy

#### The following are the sites that we need to confirm if they are working correctly
**Task:**
Check if you can log into the following sites

- [ ] - hellomwana-zimbabwe.ona.io
- [ ] - cpims-cambodia.ona.io
- [ ] - philippines.ona.io
- [ ] - globalcommunities.onalabs.org
- [ ] - ingc-mozambique.onalabs.org
- [ ] - zimbabwe.ona.io
- [ ] - shinesomalia.onalabs.org
- [ ] - cycloneidai.onalabs.org
- [ ] - somreport.ona.io
- [ ] - somnutritionsites.ona.io
