### ISSUE TITLE
Map State to URL Params

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#52]
Currently the URL never changes and the map will always initialize with the default state outlined by the MapSpec. Moving forward it we will need to (re-)initialize a map with any given state based on state parameters which can be stashed in the URL query.

**Comment by cKellyDesign** [comment]
- [ ] Define MVP params
- [ ] Define stretch params
- [ ] Set state on runtime based on URL params

**Comment by kahummer** [comment]
@cKellyDesign we may need clairity on mvp params and stretch params. We had a discussion with @kelvin-muchiri  and this is what we discussed:

Push layerIds to URL on selection. (this may introduce very lengthy URLs which may be addressed by hashing the id's to shorten the URLs).
Load the layers from URLs on the component mount to avoid re-rendering when pushing the layerIds
Have a share icon on the title bar or under map controls that allows user to share the site

**Comment by cKellyDesign** [comment]
### MVP Params
> @cKellyDesign we may need clairity on mvp params and stretch params.

- [ ] **`layers`** - a comma separated list of layer ids
- [ ] **`zoom`** - a number representing the current zoom level
- [ ] **`center`** -  a comma sperated pair of coordinates `lng, lat`

**Comment by cKellyDesign** [comment]
### Core Implementation
@kahummer @kelvin-muchiri it feels like we can take one of a few approaches (ordered by increasing complexity and effort):
1. Gisida only builds a shareable URL when clicking the share button
2. Gisida constantly updates URL and builds the URL based on local state
3. Gisida navigates to these URLs which updates the local state

For 1 and 2, Gisida would read the URL params before initializing anything and use that to overwrite the site-config's default settings.

2 and 3 are essentially the same but reversed roles. For 3 it feels like we would have to completely restructure our current pub-sub model to draw its logic from the URL so may be better in Gisida 2.0 (if not 3.0).

### Client Implementation
Since we have to consider a wide variety of contexts, our approach will need to be configurable.
```js
// site-config.json
{
    ...
    mapStateToURL: false, // true enables the functionality
}

@kahummer @kelvin-muchiri - One thing I'm not clear on is which repo / components should be responsible for updating the URL. Thoughts?

**Comment by kahummer** [comment]
@cKellyDesign @kelvin-muchiri I think adding pushing the layer ids as params can come once a user selects a checkbox. I think adding this on the layer component that toggles layers once selected would be a nice spot. 
```
if (layer && layer.visible === false) {
      const pageUrl = `${window.location.href}?${layer.id} `
      history.pushState('', '', pageUrl);
    } else if (layer && layer.visible === true) {
      const popedLayer = window.location.href.replace(`?${layer.id}`, '');
      history.replaceState('', '', popedLayer);
    } 
```
To add the layer id's to the url
resulting to such a url 
![Screenshot from 2020-04-15 14-53-09](https://user-images.githubusercontent.com/16018123/79334796-a2352500-7f29-11ea-9b59-443a687b3bc4.png).
I'm not sure how we should handle the default layers. Currently, when they are unchecked the above implementation won't take that into consideration. Are there scenarios we would want to share maps without some default layers or we can have the bare minimum working then put this into consideration.

In relation to the params, I think the URL would be able to load the zoom and lat, long from the location prop on the layer spec or stick to what is provided on the config file. I think Getting the specific zoom and center may mean debouncing when zoom stops and pushing this to the URL. I think we can look into this once we hack loading the layers from the url

I'm yet to establish the right spot to toggle the layers from the URL.

**Comment by kelvin-muchiri** [comment]
> Are there scenarios we would want to share maps without some default layers or we can have the bare minimum working then put this into consideration.

Then in that case  I think we would not show a default layer if it was not part of the selection.

**Comment by kelvin-muchiri** [comment]
@cKellyDesign What do you think of the hashing then unpacking the URL to avoid having long URLs? Is it a feasible approach?

**Comment by cKellyDesign** [comment]
> What do you think of hashing then unpacking the URL to avoid having long URLs? Is it a feasible approach?

@kelvin-muchiri I'd say for now maybe we don't need to worry about long URLs? Unless, is there some reason long urls are bad (other than human readability)?

**Comment by cKellyDesign** [comment]
@kahummer @kelvin-muchiri please structure the url as such:
`/?layers=<string,string,string>&zoom=<number>&center=<lng number,lat number>`

so that might look like:
`/?layers=layerA,layerB,layerX&zoom=8&center=10,10`

**Comment by kelvin-muchiri** [comment]
> I'd say for now maybe we don't need to worry about long URLs? Unless, is there some reason long urls are bad (other than human readability)?

Agreed

**Comment by kelvin-muchiri** [comment]
@cKellyDesign @kahummer So what about sites with oauth or at the moment the scope is limited to sites without oauth?

**Comment by kelvin-muchiri** [comment]
> Are there scenarios we would want to share maps without some default layers or we can have the bare minimum working then put this into consideration.

So I think just to clarify, there are two kinds of default layers. Boundaries and Labels and Data layers (Like the default layer on the map when you load http://philippines.onalabs.org/). I think boundaries and labels should always load but we should not load the default data layers if they are not in the shared URL.

**Comment by cKellyDesign** [comment]
> So what about sites with oauth

Seems like the router should redirect the user to the login page if they're not logged in. After logging in it would be nice if the app redirected back to the URL.

> I think boundaries and labels should always load

Seems like the URL should have these layers included and toggle like any other layer?

**Comment by kelvin-muchiri** [comment]
> Seems like the router should redirect the user to the login page if they're not logged in. After logging in it would be nice if the app redirected back to the URL.

Ok
